services:
  build-kernel:
    image: build-kernel
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile

  build-dummy:
    image: build-dummy
    build:
      context: ./build-dummy
      dockerfile: ./Dummy.Dockerfile

  qemu-base:
    image: qemu-base
    build:
      context: ./reproducer
      dockerfile: ./qemu-base.Dockerfile
