services:
  build-kernel:
    image: build-kernel
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile

  build-dummy:
    image: build-dummy
    build:
      context: ./build-dummy
      dockerfile: ./Dummy.Dockerfile

  reproducer:
    image: reproducer
    build:
      context: ./reproducer
      dockerfile: ./Reproduce.Dockerfile
