services:
  build-kernel:
    image: build-kernel
    build:
      context: .
      dockerfile: ./build-kernel/Build.Dockerfile

  build-dummy:
    image: build-dummy
    build:
      context: .
      dockerfile: ./build-dummy/Dummy.Dockerfile