include:
  - clang-images.yml
  - gcc-images.yml
services:
#  build-dummy:
#    image: build-dummy
#    build:
#      context: ./build-dummy
#      dockerfile: ./Dummy.Dockerfile

  reproducer:
    image: reproducer
    build:
      context: ./reproducer
      dockerfile: ./Reproduce.Dockerfile
