services:
  gcc-5:
    image: karyeet/rgym:gcc-5
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile
      args:
        CC_BASE_IMAGE: gcc
        CC_IMAGE_VERSION: 5
  gcc-6:
    image: karyeet/rgym:gcc-6
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile
      args:
        CC_BASE_IMAGE: gcc
        CC_IMAGE_VERSION: 6
  gcc-7:
    image: karyeet/rgym:gcc-7
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile
      args:
        CC_BASE_IMAGE: gcc
        CC_IMAGE_VERSION: 7
  gcc-8:
    image: karyeet/rgym:gcc-8
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile
      args:
        CC_BASE_IMAGE: gcc
        CC_IMAGE_VERSION: 8
  gcc-9:
    image: karyeet/rgym:gcc-9
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile
      args:
        CC_BASE_IMAGE: gcc
        CC_IMAGE_VERSION: 9
  gcc-10:
    image: karyeet/rgym:gcc-10
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile
      args:
        CC_BASE_IMAGE: gcc
        CC_IMAGE_VERSION: 10
  gcc-11:
    image: karyeet/rgym:gcc-11
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile
      args:
        CC_BASE_IMAGE: gcc
        CC_IMAGE_VERSION: 11
  gcc-12:
    image: karyeet/rgym:gcc-12
    build:
      context: ./build-kernel
      dockerfile: ./Build.Dockerfile
      args:
        CC_BASE_IMAGE: gcc
        CC_IMAGE_VERSION: 12