name: Build and Push Docker Images

on:
  push:
    branches: [ main, older-compiler-support ]
    paths:
      - 'Docker/**'
      - '.github/workflows/docker-build-push.yml'
  workflow_dispatch:

jobs:
  build-gcc:
    name: GCC ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [5, 6, 7, 8, 9, 10, 11, 12 ]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push gcc-${{ matrix.version }}
        uses: docker/bake-action@v5
        with:
          workdir: Docker
          files: |
            docker-compose.yml
            gcc-images.yml
            clang-images.yml
          targets: gcc-${{ matrix.version }}
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  build-clang:
    name: Clang ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ 9, 10, 11, 12, 13, 14, 15 ]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push clang-${{ matrix.version }}
        uses: docker/bake-action@v5
        with:
          workdir: Docker
          files: |
            docker-compose.yml
            gcc-images.yml
            clang-images.yml
          targets: clang-${{ matrix.version }}
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  build-reproducer:
    name: Reproducer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push reproducer
        uses: docker/bake-action@v5
        with:
          workdir: Docker
          files: |
            docker-compose.yml
            gcc-images.yml
            clang-images.yml
          targets: reproducer
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max